config : [
   workers : 2,
   id : 'default',
   batch_size: 125,
   batch_timeout: 50
]

input : [
  twitter : {
    access_key : "",
    access_token : ""
  }
]

filter : [

]

output : [
  cassandra : {
    host : ["127.0.0.1"],
    port : 80,
    keyspace : "",
    schema : ""
  }
]